include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI for Radius Monitor
LUCI_DEPENDS:=+luci +luci-base +git +git-http
LUCI_DESCRIPTION:=Application for monitoring RADIUS server.

PKG_MAINTAINER:=Maizil <maizilpc7@gmail.com>
PKG_VERSION:=2.3
PKG_LICENSE:=Apache-2.0

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature